name: code_ground
description: "A new Flutter project."
# This project is private and won't be published to pub.dev.
publish_to: 'none' # To publish, remove this line.

# Versioning for the application.
# Follows major.minor.patch+buildNumber format.
version: 1.0.0+1

# Specifies the Dart SDK version required for this project.
environment:
  sdk: ^3.5.4

# Dependencies used by the application.
dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk: ^1.9.5 # Kakao SDK for various Kakao platform APIs.
  kakao_flutter_sdk_user: ^1.9.5 # Kakao User API for login.
  kakao_flutter_sdk_share: ^1.9.5 # Kakao Share API for sharing content.
  kakao_flutter_sdk_talk: ^1.9.5 # KakaoTalk API for messages and social features.
  kakao_flutter_sdk_friend: ^1.9.5 # Kakao Friends Picker API.
  kakao_flutter_sdk_navi: ^1.9.5 # KakaoNavi API for navigation services.

  google_sign_in: ^6.2.2 # Google Sign-In for authentication.

  firebase_core: ^3.8.0 # Core Firebase functionalities.
  firebase_auth: ^5.3.3 # Firebase Authentication API.
  cloud_firestore: ^5.5.0 # Firebase Cloud Firestore API.
  firebase_database: ^11.1.5 # Firebase Realtime Database API.

  webview_flutter: ^4.9.0

  http: ^1.2.2 # http 통신 기능 추가
  provider: ^6.1.2  # 프로바이더 추가

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  fluttertoast: ^8.0.9 # 토스트 위젯 추가
  cupertino_icons: ^1.0.8 # IOS 모양 위젯 추가
  shared_preferences: ^2.3.2
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true # Enables the use of Material Design icons.

  assets:
    - assets/images/ # Directory for image assets.
    - assets/images/languages/ # Subdirectory for language-specific images.
    - assets/logo/ # Directory for logos.

  # Fonts can be added here by defining their families and styles.
  # Example structure is included but commented out.
