name: code_ground
description: "A new Flutter project."
# This project is private and won't be published to pub.dev.
publish_to: 'none' # To publish, remove this line.

# Versioning for the application.
# Follows major.minor.patch+buildNumber format.
version: 1.0.0+1

# Specifies the Dart SDK version required for this project.
environment:
  sdk: ^3.5.4

# Dependencies used by the application.
dependencies:
  flutter:
    sdk: flutter
  kakao_flutter_sdk: ^1.9.5 # Kakao SDK for various Kakao platform APIs.
  kakao_flutter_sdk_user: ^1.9.5 # Kakao User API for login.
  kakao_flutter_sdk_share: ^1.9.5 # Kakao Share API for sharing content.
  kakao_flutter_sdk_talk: ^1.9.5 # KakaoTalk API for messages and social features.
  kakao_flutter_sdk_friend: ^1.9.5 # Kakao Friends Picker API.
  kakao_flutter_sdk_navi: ^1.9.5 # KakaoNavi API for navigation services.

  google_sign_in: ^6.2.2 # Google Sign-In for authentication.

  firebase_core: ^3.8.0 # Core Firebase functionalities.
  firebase_auth: ^5.3.3 # Firebase Authentication API.
  cloud_firestore: ^5.5.0 # Firebase Cloud Firestore API.
  firebase_database: ^11.1.5 # Firebase Realtime Database API.

  webview_flutter: ^4.9.0 # WebView support for embedding web content.

  http: ^1.2.2 # HTTP client for making network requests.
  provider: ^6.1.2  # State management solution using the Provider package.

  fluttertoast: ^8.0.9 # Package for displaying toast messages.
  cupertino_icons: ^1.0.8 # Icons package for iOS-style components.
  shared_preferences: ^2.3.2 # Local storage for simple key-value data.
  intl: ^0.19.0 # Internationalization and localization utilities.
  collection: ^1.18.0 # Collection utilities for Dart.
  crypto: ^3.0.6

  flutter_local_notifications:
  permission_handler:
  timezone:
  google_mobile_ads: ^5.2.0

# Development-only dependencies used for testing and linting.
dev_dependencies:
  flutter_test: 
    sdk: flutter # Flutter's test framework for unit and widget testing.

  flutter_lints: ^5.0.0 # A collection of lints to encourage good coding practices.

# Flutter-specific configurations for assets and fonts.
flutter:
  uses-material-design: true # Enables the use of Material Design icons.

  assets:
    - assets/images/ # Directory for image assets.
    - assets/images/languages/ # Subdirectory for language-specific images.
    - assets/logo/ # Directory for logos.

  # Fonts can be added here by defining their families and styles.
  # Example structure is included but commented out