// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtKs6ZPePUTsYnPmo7Nm5M8J2n2nbwbz0',
    appId: '1:278986162898:web:c7d8414a7f04af28f7a30b',
    messagingSenderId: '278986162898',
    projectId: 'oss-code-ground',
    authDomain: 'oss-code-ground.firebaseapp.com',
    storageBucket: 'oss-code-ground.firebasestorage.app',
    measurementId: 'G-413Z25PK40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFXtHOp0H3-aEkG7AILjlmZiWf-RVvic',
    appId: '1:278986162898:android:829378f3d8488e40f7a30b',
    messagingSenderId: '278986162898',
    projectId: 'oss-code-ground',
    storageBucket: 'oss-code-ground.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQCMXjVgAQNUWBKZbxkikEwq2SslX1Gc',
    appId: '1:278986162898:ios:f72ac216218cd640f7a30b',
    messagingSenderId: '278986162898',
    projectId: 'oss-code-ground',
    storageBucket: 'oss-code-ground.firebasestorage.app',
    iosBundleId: 'com.oss.codeGround',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoQCMXjVgAQNUWBKZbxkikEwq2SslX1Gc',
    appId: '1:278986162898:ios:f72ac216218cd640f7a30b',
    messagingSenderId: '278986162898',
    projectId: 'oss-code-ground',
    storageBucket: 'oss-code-ground.firebasestorage.app',
    iosBundleId: 'com.oss.codeGround',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtKs6ZPePUTsYnPmo7Nm5M8J2n2nbwbz0',
    appId: '1:278986162898:web:8c852220251369d4f7a30b',
    messagingSenderId: '278986162898',
    projectId: 'oss-code-ground',
    authDomain: 'oss-code-ground.firebaseapp.com',
    storageBucket: 'oss-code-ground.firebasestorage.app',
    measurementId: 'G-WMC08GLYER',
  );
}
